#!/usr/bin/env python3
"""Plot a two-dimensional field from a FlexCTM snapshot or merged file."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr


TIME_DIMS = ("time", "Time")
VERTICAL_DIMS = ("z", "layer", "lev", "level", "bottom_top")
COORDINATE_PAIRS = (
    ("mlon", "mlat"),
    ("lon", "lat"),
    ("longitude", "latitude"),
    ("XLONG", "XLAT"),
)


def parse_levels(text: str) -> list[float]:
    try:
        values = [float(value) for value in text.split(",")]
    except ValueError as error:
        raise argparse.ArgumentTypeError("levels must be comma-separated numbers") from error
    if len(values) < 2 or any(right <= left for left, right in zip(values, values[1:])):
        raise argparse.ArgumentTypeError("levels must contain at least two increasing values")
    return values


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot one FlexCTM variable from a snapshot or merged file.",
    )
    parser.add_argument("input", help="Snapshot or merged NetCDF file.")
    parser.add_argument("variable", help="Variable to plot.")
    parser.add_argument(
        "--grid",
        help="Static-grid file containing mlat and mlon; recommended for model output.",
    )
    parser.add_argument("--time-index", type=int, help="Zero-based time index; default: 0.")
    parser.add_argument(
        "--all-times",
        action="store_true",
        help="Plot a range of time indices in one process.",
    )
    parser.add_argument(
        "--start-time-index",
        type=int,
        default=0,
        help="First time index for --all-times; default: 0.",
    )
    parser.add_argument(
        "--end-time-index",
        type=int,
        help="Last time index for --all-times; default: the final time.",
    )
    parser.add_argument("--level", type=int, default=0, help="Zero-based vertical level.")
    parser.add_argument("-o", "--output", help="PNG path; a name is generated by default.")
    parser.add_argument(
        "--output-dir",
        help="Directory for generated PNG files; useful with --all-times.",
    )
    parser.add_argument(
        "--coastlines",
        action="store_true",
        help="Add Cartopy coastlines; the first use may download Natural Earth data.",
    )
    parser.add_argument("--title", help="Custom figure title.")
    parser.add_argument("--cmap", default="viridis", help="Matplotlib colour map.")
    parser.add_argument("--levels", type=parse_levels, help="Comma-separated contour levels.")
    parser.add_argument("--vmin", type=float, help="Minimum colour value.")
    parser.add_argument("--vmax", type=float, help="Maximum colour value.")
    parser.add_argument("--dpi", type=int, default=200, help="Output resolution.")
    return parser.parse_args()


def find_dimension(data: xr.DataArray, candidates: tuple[str, ...]) -> str | None:
    return next((name for name in candidates if name in data.dims), None)


def select_field(
    data: xr.DataArray, time_index: int, level_index: int
) -> tuple[xr.DataArray, str | None, str | None]:
    time_dim = find_dimension(data, TIME_DIMS)
    time_label = None
    if time_dim:
        if not 0 <= time_index < data.sizes[time_dim]:
            raise ValueError(f"time index {time_index} is outside 0..{data.sizes[time_dim] - 1}")
        coordinate = data.coords.get(time_dim)
        if coordinate is not None:
            value = coordinate.values[time_index]
            if np.issubdtype(np.asarray(value).dtype, np.datetime64):
                time_label = np.datetime_as_string(value, unit="s").replace("T", " ")
            else:
                time_label = str(value)
        data = data.isel({time_dim: time_index})

    vertical_dim = find_dimension(data, VERTICAL_DIMS)
    level_label = None
    if vertical_dim:
        if not 0 <= level_index < data.sizes[vertical_dim]:
            raise ValueError(f"level {level_index} is outside 0..{data.sizes[vertical_dim] - 1}")
        level_label = f"{vertical_dim}={level_index}"
        data = data.isel({vertical_dim: level_index})

    data = data.squeeze(drop=True)
    if data.ndim != 2:
        raise ValueError(
            f"selected field must be two-dimensional; remaining dimensions: {data.dims}"
        )
    return data, time_label, level_label


def coordinates_from_dataset(dataset: xr.Dataset) -> tuple[np.ndarray, np.ndarray] | None:
    for longitude_name, latitude_name in COORDINATE_PAIRS:
        if longitude_name not in dataset or latitude_name not in dataset:
            continue
        longitude = np.asarray(dataset[longitude_name].squeeze().values)
        latitude = np.asarray(dataset[latitude_name].squeeze().values)
        if longitude.ndim == latitude.ndim == 1:
            longitude, latitude = np.meshgrid(longitude, latitude)
        if longitude.ndim == latitude.ndim == 2:
            return longitude, latitude
    return None


def load_coordinates(
    dataset: xr.Dataset, grid_path: str | None, shape: tuple[int, int]
) -> tuple[np.ndarray, np.ndarray, bool]:
    if grid_path:
        with xr.open_dataset(grid_path, engine="netcdf4") as grid:
            coordinates = coordinates_from_dataset(grid)
        if coordinates is None:
            raise ValueError(f"{grid_path} does not contain a supported longitude/latitude pair")
    else:
        coordinates = coordinates_from_dataset(dataset)

    if coordinates is None:
        y, x = np.indices(shape)
        return x, y, False
    if coordinates[0].shape != shape or coordinates[1].shape != shape:
        raise ValueError(
            f"coordinate shape {coordinates[0].shape} does not match field shape {shape}"
        )
    return coordinates[0], coordinates[1], True


def default_output_name(input_path: Path, variable: str, time_index: int, level: int) -> Path:
    return input_path.with_name(f"{input_path.stem}_{variable}_t{time_index:03d}_z{level:03d}.png")


def select_time_indices(data: xr.DataArray, args: argparse.Namespace) -> list[int]:
    time_dim = find_dimension(data, TIME_DIMS)
    if not args.all_times:
        if args.end_time_index is not None or args.start_time_index != 0:
            raise ValueError("--start-time-index and --end-time-index require --all-times")
        return [0 if args.time_index is None else args.time_index]

    if args.time_index is not None:
        raise ValueError("--time-index cannot be combined with --all-times")
    if args.output:
        raise ValueError("--output cannot be combined with --all-times; use --output-dir")
    if time_dim is None:
        raise ValueError("--all-times requires a variable with a time dimension")

    last_index = data.sizes[time_dim] - 1
    end_index = last_index if args.end_time_index is None else args.end_time_index
    if not 0 <= args.start_time_index <= end_index <= last_index:
        raise ValueError(
            f"time range {args.start_time_index}..{end_index} is outside 0..{last_index}"
        )
    return list(range(args.start_time_index, end_index + 1))


def load_cartopy(enabled: bool):
    if not enabled:
        return None, None
    try:
        import cartopy.crs as ccrs
        import cartopy.feature as cfeature
    except ImportError as error:
        raise ValueError("--coastlines requires Cartopy") from error
    return ccrs, cfeature


def output_path(args: argparse.Namespace, input_path: Path, time_index: int) -> Path:
    if args.output:
        return Path(args.output)
    output = default_output_name(input_path, args.variable, time_index, args.level)
    if args.output_dir:
        output = Path(args.output_dir) / output.name
    return output


def render_plot(
    args: argparse.Namespace,
    input_path: Path,
    field: xr.DataArray,
    values: np.ndarray,
    longitude: np.ndarray,
    latitude: np.ndarray,
    geographic: bool,
    time_label: str | None,
    level_label: str | None,
    time_index: int,
    ccrs,
    cfeature,
) -> Path:
    if args.coastlines and not geographic:
        raise ValueError("--coastlines requires longitude and latitude coordinates")
    unit = field.attrs.get("unit", field.attrs.get("units", ""))
    description = field.attrs.get("description", args.variable)

    if args.levels and (args.vmin is not None or args.vmax is not None):
        raise ValueError("use either --levels or --vmin/--vmax, not both")

    use_cartopy = args.coastlines
    subplot_kw = {"projection": ccrs.PlateCarree()} if use_cartopy else {}
    figure, axis = plt.subplots(figsize=(10, 5), subplot_kw=subplot_kw)
    contour_options = {"cmap": args.cmap, "extend": "both"}
    if args.levels:
        contour_options["levels"] = args.levels
    else:
        contour_options["vmin"] = args.vmin
        contour_options["vmax"] = args.vmax
    if use_cartopy:
        contour_options["transform"] = ccrs.PlateCarree()

    image = axis.contourf(longitude, latitude, values, **contour_options)
    if use_cartopy:
        axis.add_feature(cfeature.COASTLINE.with_scale("110m"), linewidth=0.7)
        gridlines = axis.gridlines(draw_labels=True, linewidth=0.3, linestyle="--", alpha=0.5)
        gridlines.top_labels = False
        gridlines.right_labels = False
    else:
        axis.set_xlabel("longitude" if geographic else "x index")
        axis.set_ylabel("latitude" if geographic else "y index")

    labels = [args.variable]
    if level_label:
        labels.append(level_label)
    if time_label:
        labels.append(time_label)
    axis.set_title(args.title or " | ".join(labels))
    colour_bar = figure.colorbar(image, ax=axis, pad=0.03)
    colour_bar.set_label(f"{description} [{unit}]" if unit else description)
    figure.tight_layout()

    output = output_path(args, input_path, time_index)
    output.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output, dpi=args.dpi, bbox_inches="tight")
    plt.close(figure)
    return output


def make_plots(args: argparse.Namespace) -> list[Path]:
    input_path = Path(args.input)
    ccrs, cfeature = load_cartopy(args.coastlines)
    outputs = []
    with xr.open_dataset(input_path, engine="netcdf4") as dataset:
        if args.variable not in dataset:
            raise ValueError(f'{input_path} does not contain variable "{args.variable}"')

        data = dataset[args.variable]
        time_indices = select_time_indices(data, args)
        coordinates = None
        for time_index in time_indices:
            field, time_label, level_label = select_field(data, time_index, args.level)
            values = np.asarray(field.values)
            if coordinates is None:
                coordinates = load_coordinates(dataset, args.grid, values.shape)
            longitude, latitude, geographic = coordinates
            outputs.append(
                render_plot(
                    args,
                    input_path,
                    field,
                    values,
                    longitude,
                    latitude,
                    geographic,
                    time_label,
                    level_label,
                    time_index,
                    ccrs,
                    cfeature,
                )
            )
    return outputs


def main() -> int:
    args = parse_arguments()
    try:
        outputs = make_plots(args)
    except (OSError, ValueError, KeyError) as error:
        print(f"plot.py: {error}", file=sys.stderr)
        return 2
    if len(outputs) == 1:
        print(f"Wrote {outputs[0]}")
    else:
        print(f"Wrote {len(outputs)} figures to {outputs[0].parent}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
