#!/usr/bin/env python3
"""Plot a two-dimensional field from a FlexCTM snapshot or merged file."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm, LinearSegmentedColormap, ListedColormap
from matplotlib.ticker import MaxNLocator
import numpy as np
import xarray as xr


TIME_DIMS = ("time", "Time")
VERTICAL_DIMS = ("z", "layer", "lev", "level", "bottom_top")
COORDINATE_PAIRS = (
    ("mlon", "mlat"),
    ("lon", "lat"),
    ("longitude", "latitude"),
    ("XLONG", "XLAT"),
)
FLEXCTM_COLOURS = ("#ffffff", "#2166ac", "#1a9850", "#fee08b", "#d73027")
COASTLINE_FILE = Path(__file__).resolve().parents[1] / "media" / "ne_110m_coastline.geojson"
WIND_VARIABLES = ("U", "V")


@dataclass
class GridInfo:
    longitude: np.ndarray
    latitude: np.ndarray
    geographic: bool
    attributes: dict


def parse_levels(text: str) -> list[float]:
    try:
        values = [float(value) for value in text.split(",")]
    except ValueError as error:
        raise argparse.ArgumentTypeError("levels must be comma-separated numbers") from error
    if len(values) < 2 or any(right <= left for left, right in zip(values, values[1:])):
        raise argparse.ArgumentTypeError("levels must contain at least two increasing values")
    return values


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot one FlexCTM variable from a snapshot or merged file.",
    )
    parser.add_argument("input", help="Snapshot or merged NetCDF file.")
    parser.add_argument("variable", help="Variable to plot.")
    parser.add_argument(
        "--grid",
        help="Static-grid file containing mlat and mlon; recommended for model output.",
    )
    parser.add_argument("--time-index", type=int, help="Zero-based time index; default: 0.")
    parser.add_argument(
        "--all-times",
        action="store_true",
        help="Plot a range of time indices in one process.",
    )
    parser.add_argument(
        "--start-time-index",
        type=int,
        default=0,
        help="First time index for --all-times; default: 0.",
    )
    parser.add_argument(
        "--end-time-index",
        type=int,
        help="Last time index for --all-times; default: the final time.",
    )
    parser.add_argument("--level", type=int, default=0, help="Zero-based vertical level.")
    parser.add_argument("-o", "--output", help="PNG path; a name is generated by default.")
    parser.add_argument(
        "--output-dir",
        help="Directory for generated PNG files; useful with --all-times.",
    )
    coastline_group = parser.add_mutually_exclusive_group()
    coastline_group.add_argument(
        "--coastlines",
        dest="coastlines",
        action="store_true",
        default=True,
        help="Draw the bundled coarse coastlines; enabled by default.",
    )
    coastline_group.add_argument(
        "--no-coastlines",
        dest="coastlines",
        action="store_false",
        help="Do not draw coastlines.",
    )
    wind_group = parser.add_mutually_exclusive_group()
    wind_group.add_argument(
        "--wind",
        dest="wind",
        action="store_true",
        default=True,
        help="Overlay U/V wind vectors when available; enabled by default.",
    )
    wind_group.add_argument(
        "--no-wind",
        dest="wind",
        action="store_false",
        help="Do not overlay wind vectors.",
    )
    parser.add_argument(
        "--wind-stride",
        type=int,
        help="Plot every Nth wind vector; selected automatically by default.",
    )
    parser.add_argument("--title", help="Custom figure title.")
    parser.add_argument(
        "--cmap",
        default="flexctm",
        help="Colour map; default: FlexCTM white-blue-green-yellow-red.",
    )
    parser.add_argument("--levels", type=parse_levels, help="Comma-separated contour levels.")
    parser.add_argument("--vmin", type=float, help="Minimum colour value.")
    parser.add_argument("--vmax", type=float, help="Maximum colour value.")
    parser.add_argument(
        "--upper-quantile",
        type=float,
        default=99.0,
        help="Percentile used as the automatic colour maximum; default: 99.",
    )
    parser.add_argument("--dpi", type=int, default=200, help="Output resolution.")
    return parser.parse_args()


def find_dimension(data: xr.DataArray, candidates: tuple[str, ...]) -> str | None:
    return next((name for name in candidates if name in data.dims), None)


def select_field(
    data: xr.DataArray, time_index: int, level_index: int
) -> tuple[xr.DataArray, str | None, str | None]:
    time_dim = find_dimension(data, TIME_DIMS)
    time_label = None
    if time_dim:
        if not 0 <= time_index < data.sizes[time_dim]:
            raise ValueError(f"time index {time_index} is outside 0..{data.sizes[time_dim] - 1}")
        coordinate = data.coords.get(time_dim)
        if coordinate is not None:
            value = coordinate.values[time_index]
            if np.issubdtype(np.asarray(value).dtype, np.datetime64):
                time_label = np.datetime_as_string(value, unit="s").replace("T", " ")
            else:
                time_label = str(value)
        data = data.isel({time_dim: time_index})

    vertical_dim = find_dimension(data, VERTICAL_DIMS)
    level_label = None
    if vertical_dim:
        if not 0 <= level_index < data.sizes[vertical_dim]:
            raise ValueError(f"level {level_index} is outside 0..{data.sizes[vertical_dim] - 1}")
        level_label = f"{vertical_dim}={level_index}"
        data = data.isel({vertical_dim: level_index})

    data = data.squeeze(drop=True)
    if data.ndim != 2:
        raise ValueError(
            f"selected field must be two-dimensional; remaining dimensions: {data.dims}"
        )
    return data, time_label, level_label


def coordinates_from_dataset(dataset: xr.Dataset) -> tuple[np.ndarray, np.ndarray] | None:
    for longitude_name, latitude_name in COORDINATE_PAIRS:
        if longitude_name not in dataset or latitude_name not in dataset:
            continue
        longitude = np.asarray(dataset[longitude_name].squeeze().values)
        latitude = np.asarray(dataset[latitude_name].squeeze().values)
        if longitude.ndim == latitude.ndim == 1:
            longitude, latitude = np.meshgrid(longitude, latitude)
        if longitude.ndim == latitude.ndim == 2:
            return longitude, latitude
    return None


def load_coordinates(
    dataset: xr.Dataset, grid_path: str | None, shape: tuple[int, int]
) -> GridInfo:
    if grid_path:
        with xr.open_dataset(grid_path, engine="netcdf4") as grid:
            coordinates = coordinates_from_dataset(grid)
            attributes = dict(grid.attrs)
        if coordinates is None:
            raise ValueError(f"{grid_path} does not contain a supported longitude/latitude pair")
    else:
        coordinates = coordinates_from_dataset(dataset)
        attributes = dict(dataset.attrs)

    if coordinates is None:
        y, x = np.indices(shape)
        return GridInfo(x, y, False, attributes)
    if coordinates[0].shape != shape or coordinates[1].shape != shape:
        raise ValueError(
            f"coordinate shape {coordinates[0].shape} does not match field shape {shape}"
        )
    return GridInfo(coordinates[0], coordinates[1], True, attributes)


def default_output_name(input_path: Path, variable: str, time_index: int, level: int) -> Path:
    return input_path.with_name(f"{input_path.stem}_{variable}_t{time_index:03d}_z{level:03d}.png")


def select_time_indices(data: xr.DataArray, args: argparse.Namespace) -> list[int]:
    time_dim = find_dimension(data, TIME_DIMS)
    if not args.all_times:
        if args.end_time_index is not None or args.start_time_index != 0:
            raise ValueError("--start-time-index and --end-time-index require --all-times")
        return [0 if args.time_index is None else args.time_index]

    if args.time_index is not None:
        raise ValueError("--time-index cannot be combined with --all-times")
    if args.output:
        raise ValueError("--output cannot be combined with --all-times; use --output-dir")
    if time_dim is None:
        raise ValueError("--all-times requires a variable with a time dimension")

    last_index = data.sizes[time_dim] - 1
    end_index = last_index if args.end_time_index is None else args.end_time_index
    if not 0 <= args.start_time_index <= end_index <= last_index:
        raise ValueError(
            f"time range {args.start_time_index}..{end_index} is outside 0..{last_index}"
        )
    return list(range(args.start_time_index, end_index + 1))


def load_cartopy():
    try:
        import cartopy.crs as ccrs
    except ImportError:
        return None
    return ccrs


def find_data_statistics(
    data: xr.DataArray,
    time_indices: list[int],
    level_index: int,
    upper_quantile: float,
) -> tuple[float, float, float]:
    if not 0.0 < upper_quantile <= 100.0:
        raise ValueError("--upper-quantile must be greater than 0 and no greater than 100")

    minimum = np.inf
    maximum = -np.inf
    samples = []
    sample_limit = max(1, 1_000_000//len(time_indices))
    for time_index in time_indices:
        field, _, _ = select_field(data, time_index, level_index)
        values = np.asarray(field.values)
        finite = values[np.isfinite(values)]
        if finite.size:
            minimum = min(minimum, float(finite.min()))
            maximum = max(maximum, float(finite.max()))
            if finite.size > sample_limit:
                positions = np.linspace(0, finite.size - 1, sample_limit, dtype=int)
                finite = finite[positions]
            samples.append(finite)
    if not np.isfinite(minimum) or not np.isfinite(maximum):
        raise ValueError("selected field does not contain finite values")
    quantile_maximum = float(np.percentile(np.concatenate(samples), upper_quantile))
    if quantile_maximum <= minimum < maximum:
        quantile_maximum = maximum
    return minimum, maximum, quantile_maximum


def make_colour_scale(
    args: argparse.Namespace,
    data_minimum: float,
    data_maximum: float,
    quantile_maximum: float,
) -> tuple[np.ndarray, np.ndarray, str]:
    if args.levels and (args.vmin is not None or args.vmax is not None):
        raise ValueError("use either --levels or --vmin/--vmax, not both")

    if args.levels:
        levels = np.asarray(args.levels)
    else:
        if args.vmin is None:
            lower = 0.0 if data_minimum >= 0.0 else np.floor(data_minimum)
        else:
            lower = args.vmin
        upper = np.ceil(quantile_maximum) if args.vmax is None else args.vmax
        if lower > upper or (lower == upper and (args.vmin is not None or args.vmax is not None)):
            raise ValueError("colour minimum must be smaller than colour maximum")
        if lower == upper:
            upper = lower + 1.0
        levels = np.linspace(lower, upper, 21)

    locator = MaxNLocator(nbins=10, integer=True)
    ticks = locator.tick_values(levels[0], levels[-1])
    ticks = ticks[(ticks >= levels[0]) & (ticks <= levels[-1])]
    if ticks.size < 2:
        ticks = np.asarray((levels[0], levels[-1]))

    below = data_minimum < levels[0]
    above = data_maximum > levels[-1]
    if below and above:
        extend = "both"
    elif below:
        extend = "min"
    elif above:
        extend = "max"
    else:
        extend = "neither"
    return levels, ticks, extend


def get_colour_map(name: str, colour_count: int):
    if name == "flexctm":
        continuous = LinearSegmentedColormap.from_list("flexctm", FLEXCTM_COLOURS, N=256)
        colours = continuous(np.linspace(0.0, 1.0, colour_count))
        return ListedColormap(colours, name="flexctm")
    try:
        return plt.get_cmap(name)
    except ValueError as error:
        raise ValueError(f'unknown colour map "{name}"') from error


def projection_identifier(attributes: dict) -> int:
    if "proj_id" in attributes:
        return int(attributes["proj_id"])
    return 1 if attributes.get("grid_mapping_name") == "lambert_conformal_conic" else 0


def is_regular_latlon_grid(grid: GridInfo) -> bool:
    middle_y = grid.longitude.shape[0]//2
    middle_x = grid.longitude.shape[1]//2
    return bool(
        np.allclose(grid.longitude, grid.longitude[middle_y:middle_y + 1, :])
        and np.allclose(grid.latitude, grid.latitude[:, middle_x:middle_x + 1])
    )


def create_map_projection(grid: GridInfo, ccrs):
    has_projection_metadata = "proj_id" in grid.attributes or "grid_mapping_name" in grid.attributes
    if grid.geographic and not has_projection_metadata and not is_regular_latlon_grid(grid):
        raise ValueError("curvilinear static grid lacks projection metadata; regenerate it with the current FlexCTM")
    if not grid.geographic or ccrs is None:
        if projection_identifier(grid.attributes) == 1:
            raise ValueError("Lambert plotting requires Cartopy; install it with pip install cartopy")
        return None
    if projection_identifier(grid.attributes) == 1:
        required = ("ref_lon", "ref_lat", "truelat1", "truelat2")
        missing = [name for name in required if name not in grid.attributes]
        if missing:
            raise ValueError(f"static grid is missing projection attributes: {', '.join(missing)}")
        return ccrs.LambertConformal(
            central_longitude=float(grid.attributes["ref_lon"]),
            central_latitude=float(grid.attributes["ref_lat"]),
            standard_parallels=(
                float(grid.attributes["truelat1"]),
                float(grid.attributes["truelat2"]),
            ),
        )
    return ccrs.PlateCarree()


def load_coastlines() -> list[np.ndarray]:
    if not COASTLINE_FILE.is_file():
        raise ValueError(f"bundled coastline file is missing: {COASTLINE_FILE}")
    with COASTLINE_FILE.open(encoding="utf-8") as stream:
        collection = json.load(stream)

    coastlines = []
    for feature in collection["features"]:
        geometry = feature["geometry"]
        if geometry["type"] == "MultiLineString":
            lines = geometry["coordinates"]
        else:
            lines = [geometry["coordinates"]]
        coastlines.extend(np.asarray(line) for line in lines)
    return coastlines


def draw_coastlines(axis, coastlines: list[np.ndarray], data_crs) -> None:
    options = {"color": "#303030", "linewidth": 0.55, "zorder": 4}
    if data_crs is not None:
        options["transform"] = data_crs
    for line in coastlines:
        axis.plot(line[:, 0], line[:, 1], **options)


def is_global_grid(longitude: np.ndarray) -> bool:
    middle_row = longitude[longitude.shape[0]//2, :]
    differences = np.diff(middle_row)
    regular_differences = np.abs(differences[np.abs(differences) < 180.0])
    if not regular_differences.size:
        return False
    spacing = float(np.median(regular_differences))
    return bool(np.isclose(spacing*longitude.shape[1], 360.0, atol=max(spacing*0.1, 1.0e-6)))


def prepare_geographic_fields(
    longitude: np.ndarray, latitude: np.ndarray, fields: list[np.ndarray]
) -> tuple[np.ndarray, np.ndarray, list[np.ndarray]]:
    middle_row = longitude[longitude.shape[0]//2, :]
    differences = np.diff(middle_row)
    regular_differences = np.abs(differences[np.abs(differences) < 180.0])
    if not regular_differences.size:
        return longitude, latitude, fields

    if is_global_grid(longitude):
        order = np.argsort(middle_row)
        longitude = longitude[:, order]
        latitude = latitude[:, order]
        fields = [field[:, order] for field in fields]
        longitude = np.concatenate((longitude, longitude[:, :1] + 360.0), axis=1)
        latitude = np.concatenate((latitude, latitude[:, :1]), axis=1)
        fields = [np.ma.concatenate((field, field[:, :1]), axis=1) for field in fields]
    elif np.any(np.abs(differences) >= 180.0):
        longitude = np.rad2deg(np.unwrap(np.deg2rad(longitude), axis=1))
    return longitude, latitude, fields


def nice_wind_speed(speed: float) -> float:
    if speed <= 0.0:
        return 0.0
    magnitude = 10.0**np.floor(np.log10(speed))
    fraction = speed/magnitude
    for candidate in (1.0, 2.0, 5.0, 10.0):
        if fraction <= candidate:
            return candidate*magnitude
    return 10.0*magnitude


def find_wind_reference(
    dataset: xr.Dataset, time_indices: list[int], level_index: int
) -> float | None:
    present = [name in dataset for name in WIND_VARIABLES]
    if not any(present):
        return None
    if not all(present):
        raise ValueError("input must contain both U and V to draw wind vectors")

    samples = []
    sample_limit = max(1, 500_000//len(time_indices))
    for time_index in time_indices:
        u_field, _, _ = select_field(dataset["U"], time_index, level_index)
        v_field, _, _ = select_field(dataset["V"], time_index, level_index)
        speed = np.hypot(np.asarray(u_field.values), np.asarray(v_field.values)).ravel()
        speed = speed[np.isfinite(speed)]
        if speed.size > sample_limit:
            positions = np.linspace(0, speed.size - 1, sample_limit, dtype=int)
            speed = speed[positions]
        if speed.size:
            samples.append(speed)
    if not samples:
        return None
    return nice_wind_speed(float(np.percentile(np.concatenate(samples), 90.0)))


def projected_grid(
    map_projection, data_crs, longitude: np.ndarray, latitude: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    points = map_projection.transform_points(data_crs, longitude, latitude)
    return points[:, :, 0], points[:, :, 1]


def padded_limits(coordinates: np.ndarray, difference_axis: int) -> tuple[float, float]:
    differences = np.abs(np.diff(coordinates, axis=difference_axis))
    finite = differences[np.isfinite(differences) & (differences > 0.0)]
    padding = 0.5*float(np.median(finite)) if finite.size else 0.0
    return float(np.nanmin(coordinates) - padding), float(np.nanmax(coordinates) + padding)


def output_path(args: argparse.Namespace, input_path: Path, time_index: int) -> Path:
    if args.output:
        return Path(args.output)
    output = default_output_name(input_path, args.variable, time_index, args.level)
    if args.output_dir:
        output = Path(args.output_dir) / output.name
    return output


def render_plot(
    args: argparse.Namespace,
    input_path: Path,
    field: xr.DataArray,
    values: np.ndarray,
    grid: GridInfo,
    wind_u: np.ndarray | None,
    wind_v: np.ndarray | None,
    wind_reference: float | None,
    time_label: str | None,
    level_label: str | None,
    time_index: int,
    colour_levels: np.ndarray,
    colour_ticks: np.ndarray,
    colour_extend: str,
    colour_map,
    map_projection,
    data_crs,
    coastlines: list[np.ndarray],
) -> Path:
    unit = field.attrs.get("unit", field.attrs.get("units", ""))
    description = field.attrs.get("description", args.variable)
    values = np.ma.masked_invalid(values)
    longitude = grid.longitude
    latitude = grid.latitude
    global_grid = grid.geographic and is_global_grid(longitude)
    plotted_fields = [values]
    if wind_u is not None and wind_v is not None:
        plotted_fields.extend((np.ma.masked_invalid(wind_u), np.ma.masked_invalid(wind_v)))
    if grid.geographic:
        longitude, latitude, plotted_fields = prepare_geographic_fields(longitude, latitude, plotted_fields)
    values = plotted_fields[0]
    if len(plotted_fields) == 3:
        wind_u, wind_v = plotted_fields[1:]

    use_cartopy = map_projection is not None
    subplot_kw = {"projection": map_projection} if use_cartopy else {}
    figure, axis = plt.subplots(figsize=(10, 5), subplot_kw=subplot_kw)
    field_x = longitude
    field_y = latitude
    field_transform = data_crs
    projected_x = None
    projected_y = None
    if use_cartopy and projection_identifier(grid.attributes) == 1:
        projected_x, projected_y = projected_grid(map_projection, data_crs, longitude, latitude)
        field_x = projected_x
        field_y = projected_y
        field_transform = map_projection

    mesh_options = {
        "cmap": colour_map,
        "norm": BoundaryNorm(colour_levels, colour_map.N, clip=True),
        "shading": "auto",
    }
    if use_cartopy:
        mesh_options["transform"] = field_transform

    image = axis.pcolormesh(field_x, field_y, values, **mesh_options)
    if args.coastlines and grid.geographic:
        draw_coastlines(axis, coastlines, data_crs if use_cartopy else None)

    if wind_u is not None and wind_v is not None and wind_reference:
        stride = args.wind_stride or max(1, int(np.ceil(max(values.shape)/30)))
        wind_options = {
            "color": "#202020",
            "pivot": "middle",
            "scale": 20.0*wind_reference,
            "scale_units": "width",
            "width": 0.0022,
            "headwidth": 3.5,
            "zorder": 5,
        }
        if use_cartopy:
            wind_options["transform"] = data_crs
        vectors = axis.quiver(
            longitude[::stride, ::stride],
            latitude[::stride, ::stride],
            wind_u[::stride, ::stride],
            wind_v[::stride, ::stride],
            **wind_options,
        )
        axis.quiverkey(
            vectors, 0.88, 1.025, wind_reference, f"{wind_reference:g} m s$^{{-1}}$", labelpos="E"
        )

    if use_cartopy:
        if global_grid:
            axis.set_global()
        elif projected_x is not None and projected_y is not None:
            axis.set_xlim(*padded_limits(projected_x, difference_axis=1))
            axis.set_ylim(*padded_limits(projected_y, difference_axis=0))
        else:
            extent = [
                float(np.nanmin(grid.longitude)),
                float(np.nanmax(grid.longitude)),
                float(np.nanmin(grid.latitude)),
                float(np.nanmax(grid.latitude)),
            ]
            axis.set_extent(extent, crs=data_crs)
        gridlines = axis.gridlines(
            draw_labels=True,
            x_inline=False,
            y_inline=False,
            linewidth=0.3,
            linestyle="--",
            alpha=0.5,
        )
        gridlines.top_labels = False
        gridlines.right_labels = False
        gridlines.rotate_labels = False
    else:
        if grid.geographic:
            axis.set_xlim(float(np.nanmin(longitude)), float(np.nanmax(longitude)))
            axis.set_ylim(float(np.nanmin(latitude)), float(np.nanmax(latitude)))
        axis.set_xlabel("longitude" if grid.geographic else "x index")
        axis.set_ylabel("latitude" if grid.geographic else "y index")

    labels = [args.variable]
    if level_label:
        labels.append(level_label)
    if time_label:
        labels.append(time_label)
    axis.set_title(args.title or " | ".join(labels))
    colour_bar = figure.colorbar(image, ax=axis, pad=0.03, ticks=colour_ticks, extend=colour_extend)
    colour_bar.set_label(f"{description} [{unit}]" if unit else description)
    figure.tight_layout()

    output = output_path(args, input_path, time_index)
    output.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output, dpi=args.dpi, bbox_inches="tight")
    plt.close(figure)
    return output


def make_plots(args: argparse.Namespace) -> list[Path]:
    input_path = Path(args.input)
    if args.wind_stride is not None and args.wind_stride <= 0:
        raise ValueError("--wind-stride must be a positive integer")
    ccrs = load_cartopy()
    coastlines = load_coastlines() if args.coastlines else []
    outputs = []
    with xr.open_dataset(input_path, engine="netcdf4") as dataset:
        if args.variable not in dataset:
            raise ValueError(f'{input_path} does not contain variable "{args.variable}"')

        data = dataset[args.variable]
        time_indices = select_time_indices(data, args)
        data_minimum, data_maximum, quantile_maximum = find_data_statistics(
            data, time_indices, args.level, args.upper_quantile
        )
        colour_levels, colour_ticks, colour_extend = make_colour_scale(
            args, data_minimum, data_maximum, quantile_maximum
        )
        colour_map = get_colour_map(args.cmap, len(colour_levels) - 1)
        wind_reference = find_wind_reference(dataset, time_indices, args.level) if args.wind else None
        if args.wind and wind_reference is None:
            print("plot.py: U/V not found; wind vectors were omitted", file=sys.stderr)
        grid = None
        map_projection = None
        data_crs = None
        for time_index in time_indices:
            field, time_label, level_label = select_field(data, time_index, args.level)
            values = np.asarray(field.values)
            if grid is None:
                grid = load_coordinates(dataset, args.grid, values.shape)
                map_projection = create_map_projection(grid, ccrs)
                if ccrs is not None and grid.geographic:
                    data_crs = ccrs.PlateCarree()
            wind_u = None
            wind_v = None
            if wind_reference is not None:
                u_field, _, _ = select_field(dataset["U"], time_index, args.level)
                v_field, _, _ = select_field(dataset["V"], time_index, args.level)
                wind_u = np.asarray(u_field.values)
                wind_v = np.asarray(v_field.values)
                if wind_u.shape != values.shape or wind_v.shape != values.shape:
                    raise ValueError("U/V shape does not match the plotted field")
            outputs.append(
                render_plot(
                    args,
                    input_path,
                    field,
                    values,
                    grid,
                    wind_u,
                    wind_v,
                    wind_reference,
                    time_label,
                    level_label,
                    time_index,
                    colour_levels,
                    colour_ticks,
                    colour_extend,
                    colour_map,
                    map_projection,
                    data_crs,
                    coastlines,
                )
            )
    return outputs


def main() -> int:
    args = parse_arguments()
    try:
        outputs = make_plots(args)
    except (OSError, ValueError, KeyError) as error:
        print(f"plot.py: {error}", file=sys.stderr)
        return 2
    if len(outputs) == 1:
        print(f"Wrote {outputs[0]}")
    else:
        print(f"Wrote {len(outputs)} figures to {outputs[0].parent}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
